# Generated by Django 3.1.4 on 2020-12-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, unique=True)),
                ('last_name', models.CharField(max_length=60, unique=True)),
                ('phone_no', models.CharField(max_length=60, unique=True)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
