# Generated by Django 3.1.4 on 2020-12-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_auto_20201219_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
