# Generated by Django 3.1.4 on 2020-12-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_auto_20201223_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone_no',
            field=models.CharField(max_length=60),
        ),
    ]
