# Generated by Django 3.1.4 on 2021-01-05 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_additem'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additem',
            name='select_type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additem',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='username', to='authen.register'),
            preserve_default=False,
        ),
    ]
