# Generated by Django 3.1.4 on 2021-01-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0008_auto_20210106_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='username',
        ),
    ]
