# Generated by Django 3.1.4 on 2021-01-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0009_remove_additem_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='user',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additem',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
