# Generated by Django 3.1.4 on 2021-01-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0010_auto_20210108_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additem',
            old_name='select_type',
            new_name='category',
        ),
    ]
