# Generated by Django 3.1.4 on 2021-01-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0011_auto_20210108_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='category',
        ),
    ]
