# Generated by Django 3.1.4 on 2021-01-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0014_remove_additem_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='category',
            field=models.CharField(choices=[('chairs', 'Chairs'), ('armchairs', 'Armchairs'), ('chaiselongues', 'Chaiselongues'), ('sofas', 'Sofas'), ('wardrobes', 'Wardrobes'), ('beds', 'Beds'), ('shelving units', 'Shelving Units'), ('tables', 'Tables')], max_length=70),
        ),
    ]
