# Generated by Django 3.1.5 on 2021-01-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_additem_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='additem',
            name='user_name',
        ),
    ]
