# Generated by Django 3.1.5 on 2021-01-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210112_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='reviews'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
