# Generated by Django 3.1.5 on 2021-01-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_reviews_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='reviews'),
        ),
    ]
