# Generated by Django 3.1.5 on 2021-01-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210112_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='category',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
