# Generated by Django 3.1.5 on 2021-01-13 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_reviews_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='reviews')),
                ('rating', models.IntegerField()),
                ('category', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Seller_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
