# Generated by Django 3.1.5 on 2021-01-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_product_rating_seller_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_rating',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
