# Generated by Django 3.1.5 on 2021-01-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dashboard')),
                ('description', models.CharField(max_length=2000)),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(choices=[('chairs', 'Chairs'), ('armchairs', 'Armchairs'), ('chaiselongues', 'Chaiselongues'), ('sofas', 'Sofas'), ('wardrobes', 'Wardrobes'), ('beds', 'Beds'), ('shelving units', 'Shelving Units'), ('tables', 'Tables')], max_length=70)),
            ],
        ),
    ]
