# Generated by Django 3.1.5 on 2021-01-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_additem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='user',
        ),
    ]
