# Generated by Django 3.1.5 on 2021-01-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_reviews_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='img',
        ),
    ]
