# Generated by Django 3.1.5 on 2021-01-10 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210110_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='additem',
            name='user_name',
        ),
    ]
