# Generated by Django 3.1.4 on 2021-01-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210111_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='quantity_ordered',
        ),
    ]
