# Generated by Django 3.1.4 on 2021-01-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20210111_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='total',
        ),
    ]
