# Generated by Django 3.1.4 on 2021-01-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_add_to_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
