# Generated by Django 3.1.4 on 2021-01-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_add_to_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_for_user',
            name='total_paid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
