# Generated by Django 3.1.4 on 2021-01-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total_for_user',
            name='total_paid',
        ),
        migrations.AddField(
            model_name='add_to_cart',
            name='paid',
            field=models.FloatField(default=models.FloatField(default=models.FloatField(default=0))),
        ),
        migrations.AlterField(
            model_name='add_to_cart',
            name='total',
            field=models.FloatField(default=models.FloatField(default=0)),
        ),
    ]
