# Generated by Django 3.1.4 on 2021-01-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20210111_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='paid',
            field=models.FloatField(),
        ),
    ]
