# Generated by Django 3.1.4 on 2021-01-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20210111_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
