# Generated by Django 3.1.5 on 2021-01-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_additem_user_name'),
        ('home', '0003_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.additem'),
        ),
    ]
