# Generated by Django 3.1.4 on 2021-01-12 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='total_paid',
        ),
    ]
