# Generated by Django 3.1.4 on 2021-01-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_total_for_user_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quantity',
        ),
        migrations.AddField(
            model_name='total_for_user',
            name='quantity_ordered',
            field=models.IntegerField(default=1),
        ),
    ]
