# Generated by Django 3.1.4 on 2021-01-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20210111_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='add_to_cart',
            name='total',
            field=models.FloatField(default=models.FloatField(default=0)),
        ),
    ]
