# Generated by Django 3.1.4 on 2021-01-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_auto_20210111_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='paid_amount',
        ),
    ]
