# Generated by Django 3.1.5 on 2021-01-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_additem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
