# Generated by Django 3.1.5 on 2021-01-10 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210110_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='user_name',
        ),
    ]
