# Generated by Django 3.1.4 on 2021-01-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_total_for_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_to_cart',
            old_name='quantity',
            new_name='quantity_ordered',
        ),
        migrations.AddField(
            model_name='add_to_cart',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
