# Generated by Django 3.1.4 on 2021-01-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_add_to_cart_quantity_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('cash', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField(default=1)),
                ('product_id', models.CharField(max_length=100000)),
            ],
        ),
    ]
