# Generated by Django 3.1.4 on 2021-01-11 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cart', '0014_auto_20210111_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_to_cart',
            old_name='paid',
            new_name='paid_amount',
            ),
    ]
