# Generated by Django 3.1.4 on 2021-01-12 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('paymentMethod', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('exp', models.DateTimeField()),
                ('cvv', models.CharField(max_length=30)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Total_for_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField(default=0)),
                ('product_id', models.CharField(max_length=100000)),
                ('quantity_ordered', models.IntegerField(default=1)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Add_to_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('product_id', models.CharField(max_length=100000)),
                ('description', models.CharField(max_length=1000)),
                ('product_quantity', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='cart')),
                ('price', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
